"""Shared constants for the local admin UI."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ENV_PATH = ROOT / ".env"
CCIM_LOG_DIR = ROOT / "tools" / "log"
HOST = "127.0.0.1"
PORT = 8090
DEFAULT_UV_EXE = (
    Path.home()
    / "AppData"
    / "Local"
    / "Programs"
    / "Python"
    / "Python310"
    / "Scripts"
    / "uv.exe"
)

ALLOWED_ENV_KEYS = [
    "CCIM_LLM_PROVIDER",
    "CCIM_LLM_MODEL",
    "CCIM_LLM_TIMEOUT_S",
    "CCIM_LLM_BASE_URL",
    "CCIM_SESSION_PREFIX",
    "CCIM_COMPRESSION_ENABLED",
    "CCIM_COMPRESSION_TRIGGER_TOKENS",
    "CCIM_COMPRESSION_TARGET_TOKENS",
    "CCIM_COMPRESSION_ENABLE_RETRIEVE",
    "CCIM_CURRENT_TURN_COMPRESSION_ENABLED",
    "CCIM_CURRENT_TURN_COMPRESSION_TRIGGER_TOKENS",
    "CCIM_CURRENT_TURN_COMPRESSION_READ_TOOLS",
    "CCIM_COMPRESSION_CLUSTER_SUMMARY_ENABLED",
    "CCIM_COMPRESSION_WRITE_GUARD_ENABLED",
    "CCIM_COMPRESSION_WRITE_GUARD_TOOLS",
]

DEFAULTS = {
    "CCIM_LLM_PROVIDER": "openai",
    "CCIM_LLM_MODEL": "gpt-5-mini",
    "CCIM_LLM_TIMEOUT_S": "300",
    "CCIM_LLM_BASE_URL": "",
    "CCIM_SESSION_PREFIX": "",
    "CCIM_COMPRESSION_ENABLED": "true",
    "CCIM_COMPRESSION_TRIGGER_TOKENS": "20000",
    "CCIM_COMPRESSION_TARGET_TOKENS": "14000",
    "CCIM_COMPRESSION_ENABLE_RETRIEVE": "false",
    "CCIM_CURRENT_TURN_COMPRESSION_ENABLED": "false",
    "CCIM_CURRENT_TURN_COMPRESSION_TRIGGER_TOKENS": "20000",
    "CCIM_CURRENT_TURN_COMPRESSION_READ_TOOLS": "Read,Grep,Glob,LS,Search",
    "CCIM_COMPRESSION_CLUSTER_SUMMARY_ENABLED": "false",
    "CCIM_COMPRESSION_WRITE_GUARD_ENABLED": "true",
    "CCIM_COMPRESSION_WRITE_GUARD_TOOLS": "Edit,MultiEdit,Write",
}
